[package]
name = "leptos-wasi-sol"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.7.7", features = ["csr"] }
console_error_panic_hook = "0.1.7"
log = "0.4.21"
wasi-sol = { path = "../../", features = ["lep"] }
wasm-logger = "0.2.0"
getrandom = { version = "0.2", features = ["js"] }
uuid = { version = "*", features = ["js"] }
