[package]
name = "wasi-sol-example"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
log = "0.4.21"
wasi-sol = { path = "../../", features = ["dio"] }
wasm-logger = "0.2.0"
dioxus = { version = "0.5", features = ["web"] }
