name: Anchor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y 
        . "$HOME/.cargo/env"
    - name: Install Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
        export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
        solana config set --url localhost
        solana config get
    - name: Install Solana Build Tools
      run: |
        curl -sSf https://raw.githubusercontent.com/solana-labs/solana/v1.17.17/install/solana-install-init.sh | sh -s - v1.18.15
    - name: Cleanup
      run: |
        : `rm -r $HOME/.cache/solana`
    - name: Install Anchor CLI
      run: |
        sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y pkg-config build-essential libudev-dev libssl-dev
        cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
        avm install latest
        avm use latest
        anchor --version
    - name: Run Integration Tests
      run: |
        export ANCHOR_WALLET="/home/runner/.config/solana/id.json"
        export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
        cd examples/todo-program && anchor test
